[versions]
# libraries
annotations = "24.1.0"

# plugins
changelog = "2.5.0"
intellijPlatform = "2.11.0"
qodana = "2023.3.1"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
